const excelTitle = {
  '姓名': 'fullname',
  '电子邮箱': 'email',
  '手机': 'phone',
  '密码': 'password',
  '别名': 'preferredName',
  '最高学历': 'highestDegree',
  '毕业院校': 'institute',
  '性别': 'gender',
  '毕业时间': 'GradYear',
  '民族': 'ethnicGroup',
  '婚姻状态': 'maritalStatus',
  '出生日期': 'BirthDate',
  '入职日': 'hireDate',
  '岗位名称': 'jobTitle',
  '职位': 'jobPosition',
  '工作地点': 'jobLocation',
  '聘任状态': 'employmentStatus',
  'surname': 'surname',
  'firstname': 'firstname',
  'email': 'email',
  'cell': 'phone',
  'password': 'password',
  'preferredname': 'preferredName',
  'highestdegree': 'highestDegree',
  'institute': 'institute',
  'gender': 'gender',
  'grad.year': 'GradYear',
  'ethnicgroup': 'ethnicGroup',
  'maritalstatus': 'maritalStatus',
  'birthdate': 'BirthDate',
  'hiredate': 'hireDate',
  'jobtitle': 'jobTitle',
  'jobposition': 'jobPosition',
  'joblocation': 'jobLocation',
  'employmentstatus': 'employmentStatus',
}

export { excelTitle };

